### ISSUE TITLE
Sponsor button not working

### ISSUE THREAD

**Issue by franko** [jmeubank/tdm-gcc#1]
The "Sponsor" button does not work, I get an error message:

```
Some errors were encountered when parsing the FUNDING.yml file:

Some users provided are not enrolled in GitHub Sponsors. Apply to Sponsors.
Learn more about formatting FUNDING.yml.
```

Otherwise, I would like to share my experience with TDM-GCC.

I appreciate a lot the work you have done with TDM-GCC. I have used the previous version but I was afraid it was no longer updated and I have switched to MSYS2 using the mingw-w64 packages for gcc and clang.

Now that TDM-GCC is back I am glad to use it again. I have tested using a separate install of msys2 (without gcc) and TDM-GCC works perfectly.

What I appreciate more about TDM-GCC is that:

- it produces by default binaries that does not require additional DLLs
- support both x86 and x86_64 targets

My problem with MSYS-provided GCC was that it was by default linking with libstd++ DLL and, more annoying, it is impossible to provide binaries that do not require the winpthread DLL. For these reason I am glad that TDM-GCC is back!

Something that I would love to have is to have TDM-GCC, just as it is currently, but as a package within MSYS2. May be using a specific tag like for the mingw64 packages. For me it would be the perfect solution because otherwise MSYS2 is a perfect working environment.

In any case I wish to thank you for your work and I will be glad to sponsor you if the button works :-)

I am not backed by a company and programming is my hobby so I wouldn't be able to sponsor with big money but I would like to provide my modest contribution.

**Comment by jmeubank** [comment]
Cheers @franko ! Appreciate the support and thanks for making TDM-GCC's first Github issue such an easy one. 👍 👍 

I spot two requests in here:
(1) Make the sponsor button work. Should be easy enough! Haha.
(2) Get TDM-GCC in the MSYS2 pacman repositories. I'm thinking something like "pacman -S tdm-gcc", where it gets installed in a sysroot that doesn't conflict with other GCC installations. This has been on my radar, and I'd also like to make it a [Scoop](https://github.com/lukesampson/scoop) and/or [Chocolatey](https://github.com/chocolatey/choco) package.

**Comment by jmeubank** [comment]
Sponsor button now links to [https://www.paypal.me/JohnMichaelEubank]. Once Github Sponsors approves me, that will also be an option! Sponsor away. 😁

**Comment by franko** [comment]
Great, thank you!

So looking forward for the pacman package :-) as for Scoop or Chocolatey I don't care at all but other people may be interested.

I am allergic to PowerShell and Microsoft stuff in general. Bash on MSYS2 or MinGW is my cup of tea.
