### ISSUE TITLE
thanks for keeping the win32API - Windows API

### ISSUE THREAD

**Issue by hermwats** [jmeubank/tdm-gcc#13]
I teach C++ at FIU and have used the TDM-GCC 5.1 compiler package for the students to install.
It sets the path and includes the win32API.  Students are required to compile the wxWidgets library for win applications used in the course.

Now TDB-GCC is at 9.2, but thank you for keeping a version with the win32API, so the students can still benefit from this great package for educational purposes.

Asking for future releases to please keep a version with the 'Windows API' available.  Great work.

Herman Watson
hwatson@fiu.edu

**Comment by jmeubank** [comment]
Hi @hermwats ,

Glad to hear that TDM-GCC is working for you. It's unlikely that the Win32 API will ever be dropped, but it's highly likely that it will be subsumed and no longer useful for instructing, so keep that in mind. :) (Do you make your students write GUI apps in assembler? By analogy, there are more useful ways to write them than wxWidgets and Win32.) If Microsoft stops supporting Win32, so will MinGW.org, MinGW-w64, and TDM-GCC.

As always, TDM-GCC is a redistribution of upstream components comprising a Windows-friendly GCC compiler suite.

**Comment by hermwats** [comment]
Thanks for your response.

From Bjarne Stroustrup's web site, these are the choices
http://www.stroustrup.com/C++.htmlC++ GUI libraries and toolkits:

   - FLTK <http://www.fltk.org/>.
   - gtkmm <http://www.gtkmm.org/>.
   - Qt <http://www.qt-project.org/>
   - WxWidgets <http://www.wxwidgets.org/>. <<<<<<
   - and many more
   <http://www.geocities.com/SiliconValley/Vista/7184/guitool.html>.

I use wxWidgets because lots of stuff was written and is still written in
it.  Much less confusing for students than Visual as a starting point.

I teach C++, STL, and Win applications in this introductory embedded C++
programming course.

BTW Microsoft calls it the 'Windows API Index' and probably have given up
on dropping it.
https://docs.microsoft.com/en-us/windows/win32/apiindex/windows-api-list

Again, thanks for your support.

Herman Watson
