### ISSUE TITLE
Old version of fmaq() appears to be used

### ISSUE THREAD

**Issue by p-j-miller** [jmeubank/tdm-gcc#14]
It appears that an old version of fmaq() is supplied in this package.
Compiling and linking the version from https://fossies.org/linux/gcc/libquadmath/math/fmaq.c which describes itself as Member "gcc-9.3.0/libquadmath/math/fmaq.c" (12 Mar 2020, 9888 Bytes) of package /linux/misc/gcc-9.3.0.tar.xz: resolved the issue for me. 
Without doing this some results from fmaq() were 1 bit in error.

**Comment by jmeubank** [comment]
This will be resolved in the upcoming TDM-GCC 10.3.0 release (I hope, based on the info you provided).

**Comment by p-j-miller** [comment]
Thanks - I look forward to trying your next release
