### ISSUE TITLE
package download error

### ISSUE THREAD

**Issue by decuant** [jmeubank/tdm-gcc#19]
Hello guys,

thank you very much for your efforts on keeping this project alive, I use it rarely but I'm happy to count on it.

I was wondering to recompile Lua 5.4 on a Windows 8.0 laptop using Dev-Cpp, but I have only an old 4.9.2 TDM installation.

This is not an issue, just want to let you know that I cannot download ```TDM-GCC-9.2.0 32 bit only``` from https://jmeubank.github.io/tdm-gcc/download/, it keeps stopping with a generic 'network interrupt'.

I tried also the web download manager at that page, but no luck, I attach a screen capture.

May be it's only me, just to make you aware of the problem.

![download error](https://user-images.githubusercontent.com/7431711/86019005-5b35d680-ba26-11ea-8ad6-9a47dc33836f.png)

**Comment by decuant** [comment]
Hello,

you know, you report a problem like this and it disappears...

I was able to download the requested package. Probably it was the 10th time.

Still, when installing if the checkbox to look for updates upon install is ticked then it fails. Is that web address available?

Un-ticked it, I have successfully installed the package, Dev-Cpp compiles ok a bare bone dll.

The command ```rm.exe``` is missing from distribution, so I copied the one I have from 4.9.2 in ```bin```.

The command ```gdb.exe``` is missing (it is there, but with a different name gdb32.exe), an error pops out, I have attached the image. Made a copy and renamed it. But it is not tested because my project is a DLL and I don't have a host application.

![start error](https://user-images.githubusercontent.com/7431711/86037575-d952a700-ba3f-11ea-8317-68ef68379745.png)

The makefile:

RM       = rm.exe -f

clean: clean-custom
	${RM} $(OBJ) $(BIN) $(DEF) $(STATIC)

See, Dev-Cpp is discontinued but tight to C/C++, and I just want to compile Lua 5.4.

Thank you

**Comment by jmeubank** [comment]
> The command `rm.exe` is missing from distribution, so I copied the one I have from 4.9.2 in `bin`.

This is probably an MSYS executable ; TDM-GCC can work with MSYS but does not distribute MSYS components.

> The command `gdb.exe` is missing (it is there, but with a different name gdb32.exe), an error pops out, I have attached the image. Made a copy and renamed it. But it is not tested because my project is a DLL and I don't have a host application.

https://github.com/jmeubank/tdm-distrib/blob/master/tdm32/gdb/README-gdb32-tdm.md#wrapper-executables

(Future versions of TDM-GCC may use a different folder structure to help with this.)

> The makefile:
> 
> RM = rm.exe -f
> 
> clean: clean-custom
> ${RM} $(OBJ) $(BIN) $(DEF) $(STATIC)

Probably this Makefile targets GCC running with MSYS - you can alter it to use Windows built-in executables, or find a Makefile that targets a barebones GCC-on-Windows without relying on MSYS executables like rm.exe, or install MSYS and add it to your %PATH% or merge it with TDM-GCC.

**Comment by jmeubank** [comment]
> Still, when installing if the checkbox to look for updates upon install is ticked then it fails. Is that web address available?

Works here, can you try accessing it from a different location or internet service provider? The host is Github.

**Comment by decuant** [comment]
Hi,

thank you for all your detailed answers.

I was able to compile Lua 5.4 and wxWidgets 3.1.3 , and the executables looks working properly. Using CMake exec names are recognized properly.

But for the manifest problem, no, I cannot resolve the host. I'm currently writing to you and read the horoscopes and torrenting down at 400K speed, but not your tool.

Here is the image.
![error](https://user-images.githubusercontent.com/7431711/86505544-3e9ef300-bdc6-11ea-99a3-43ca8a4c8b52.png)

Thank you for the detailed axplanations you gave me!

Antonio

**Comment by A-l-an** [comment]
Go back to the original question and remove the "check for update" checkbox. Problem solves.
