### ISSUE TITLE
dsound.h on TDM-GCC-32

### ISSUE THREAD

**Issue by sonoro1234** [jmeubank/tdm-gcc#20]
Hi,

Trying to compile with last released TDM-GCC-32 gave me error about not being able to find dsound.h
Is this expected?

Thanks for hard work!!
victor bombi

**Comment by jmeubank** [comment]
Yes, this is expected. MinGW.org & TDM32-GCC do not include dsound.h. MinGW-w64 and TDM64-GCC do.
