### ISSUE TITLE
Error when executing on 32-bit Windows XP system.

### ISSUE THREAD

**Issue by skylee03** [jmeubank/tdm-gcc#21]
When I tried to compile a C++ program which includes merely a single-line code "int main() {}" with TDM64-GCC 9.2.0 on my 64-bit Windows 10 computer, it worked well. But on a 32-bit Windows XP system, it prompted the following error message:

> C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/32/libstdc++.a: file not recognized: file format not recognized
> collect2.exe: error: ld returned 1 exit status

However, when I compile the same program with previous version of TDM64-GCC (for example, 4.9.2), it worked well on both 32-bit Windows XP and 64-bit Windows 10.

What should I do to make the TDM64-GCC 9.2.0 compiler work properly on a 32-bit Windows XP system?

**Comment by jmeubank** [comment]
It's hard to say, since you haven't provided the command line you're using.

**Comment by ScSofts** [comment]
I know that. Windows XP do not support 64bit programs.You should use ` i686 ` versions.
