### ISSUE TITLE
Unclear build instructions

### ISSUE THREAD

**Issue by mimi89999** [jmeubank/tdm-gcc#22]
> The build scripts in this package will probably not work in Cygwin, WSL, or GNU/Linux without modification.

I understand that I should build this under Windows. I see that there are POSIX shell scripts that need to be run. What shell do I need to install and run them in? The one from https://gitforwindows.org/?

**Comment by jmeubank** [comment]
No, the one from https://www.msys2.org/ , linked in the prior sentence...
