### ISSUE TITLE
Is Windows DLL Delay Load supported?

### ISSUE THREAD

**Issue by ScSofts** [jmeubank/tdm-gcc#28]
I'm trying to make a delay loaded dll example, but it doesn't work.
code:
```cpp
int __declspec(dllexport) add(int a,int b){
      return a+b;
}
```
Then
` gcc share.c -o share.dll -static -shared `

` dlltool -y libshare.a -d libshare.def `

Then I tried to compile
` gcc main.c -o delay.exe -D_WIN32_NT=0x6001 -static -L. -lshare`
But I got 
```
F:/TDM-GCC/bin/../lib/gcc/mingw32/9.2.0/../../../../mingw32/bin/ld.exe: libshare.a(dopvh.o):fake:(.text+0x9): undefined reference to `__delayLoadHelper2@8'
collect2.exe: error: ld returned 1 exit status
```

The ` libdelayimp.a ` and ` delayimp.h ` are also missing.

**Comment by jmeubank** [comment]
It looks like you're using the MinGW.org edition of TDM-GCC - there is no built-in delay load support there and you'll need to roll your own or switch to TDM64-GCC.
