### ISSUE TITLE
collect2.exe: error: ld returned 1 exit status / x86_64-w64-mingw32/bin/ld.exe: Permission denied

### ISSUE THREAD

**Issue by martobg10** [jmeubank/tdm-gcc#3]
I tried to compile this project: https://github.com/MrKrzYch00/zopfli/
But I'm not sure how to compile it. Could you help me?
I'm on Windows 10.

`D:\Downloads\zopfli-master>gcc src/zopfli/*.c -O2 -W -Wall -Wextra -ansi -pedantic -lm -o zopfli.exe
gcc: error: src/zopfli/*.c: Invalid argument`

`D:\Downloads\zopfli-master>x86_64-w64-mingw32-gcc-9.2.0.exe -O2 -W -Wall -Wextra -ansi -pedantic -lm src\zopfli -o zopfli.exe`
`C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find src\zopfli: Permission denied
collect2.exe: error: ld returned 1 exit status`

Sorry for my bad English! :(

**Comment by jmeubank** [comment]
https://lmgtfy.com/?q=gcc%3A+error%3A+src%2Fzopfli%2F*.c%3A+Invalid+argument

Triage rules; this relates to the basic operation of GCC, for which you'll find much better support elsewhere, while I continue to devote my time to TDM-GCC improvements. Best of luck! :)

**Comment by martobg10** [comment]
Okay, thank you! :)
