### ISSUE TITLE
Messy code with TDM-GCC 10.3.0 release

### ISSUE THREAD

**Issue by andrew-ares** [jmeubank/tdm-gcc#36]
Windows 10 20H2 19042.1083
![image](https://user-images.githubusercontent.com/40336192/125710698-806340cf-26e4-487f-b466-a8db041f7d5e.png)
GDB seems fine
![image](https://user-images.githubusercontent.com/40336192/125710934-a8af3601-fe34-4616-8bc9-8ea11596e9c0.png)

**Comment by waitlamp** [comment]
This might be because you set "Beta: Use Unicode UTF-8 for worldwide language support"?
