### ISSUE TITLE
Since updating - error: 'EBADMSG' was not declared in this scope; did you mean 'EBADF'?

### ISSUE THREAD

**Issue by drmclem** [jmeubank/tdm-gcc#4]
Hi

I'm assuming this is the right place for bugs now rather than sourceforge ?

I've just updated from TDM-gcc-64 (gcc 5.1.0 tdm-1)

C:/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++/x86_64-w64-mingw32/bits/error_constants.h:53:25: error: 'EBADMSG' was not declared in this scope; did you mean 'EBADF'?

and 9 similar errors with the same format but different codes such as ENOTRECOVERABLE and ETIME etc.

Thanks

Matthew

**Comment by drmclem** [comment]
Sorry - this issue is on MinGW64 
Commit [667e94]
some errnos added(PR 564)

**Comment by jmeubank** [comment]
https://sourceforge.net/p/mingw-w64/mingw-w64/ci/667e94f637a6fc6273865829a0e2dbb3ed826421/

--- a/mingw-w64-headers/crt/errno.h
+++ b/mingw-w64-headers/crt/errno.h
@@ -178,6 +178,46 @@
 #define EPROTONOSUPPORT 135
 #endif
 
+#ifndef EBADMSG
+#define EBADMSG 104
+#endif
...etc...

https://github.com/jmeubank/mingw-w64/blob/v7.x.public/mingw-w64-headers/crt/errno.h

Looks like that is present in the latest TDM-GCC release, are you using an older version of the MinGW-w64 runtime package? Can you try a clean install?

**Comment by jmeubank** [comment]
I'll close this issue shortly unless further input is provided.

**Comment by drmclem** [comment]
Hi - fully deleting my previous install (gcc 5.1.0 installer 5.1.0-2) and then re-installing rather than upgrade over it appears to have resolved this 

Thanks for your help.

**Comment by jmeubank** [comment]
Understood, it looks like the installer failed to perform a clean upgrade. I'll look into this separately.
