### ISSUE TITLE
Role of libgcc_eh.a replaced by libgcc.a

### ISSUE THREAD

**Issue by cosing** [jmeubank/tdm-gcc#47]
This results in TDM and clang not working together in Windows(clang <file> --target=x86_64-w64-mingw)
I had to repackage using ar.exe
Is this normal?
or I don't have my clang configured properly

**Comment by revelator** [comment]
had to patch out libgcc_eh from clang myself, works fine after :)

**Comment by revelator** [comment]
btw while clang itself builds fine linked to the static runtimes  libc++ and friends will not. these need to be built with -shared-libgc -shared-libstdc++ in LDFLAGS. Sadly rust is one thing that cannot be built with TDM because it relies heavily on libgcc_eh.

**Comment by revelator** [comment]
[0106-tdm-sjlj.zip](https://github.com/jmeubank/tdm-gcc/files/9594657/0106-tdm-sjlj.zip)

here is the patch for clang-14.0 need to add LDFLAGS+=" -shared-libgcc -shared-libstdc++" when building it. works just fine after that.

**Comment by revelator** [comment]
clang needs the shared runtimes hence the LDFLAGS+=" -shared-libgcc -shared-libstdc++" it cannot be built without them unless someone hacks it together (hint hard as hell to do because cmake does not think static runtimes can throw exceptions).
