### ISSUE TITLE
gdb cannot run in Windows7

### ISSUE THREAD

**Issue by MagicGeeker** [jmeubank/tdm-gcc#52]
I test tdm64-gcc-10.3.0-2.exe on Windows 7,gcc.exe is OK but gdb.exe cannot run because of missing api-ms-win-core-path-l1-1-0.dll.

**Comment by MagicGeeker** [comment]
here is the screenshot
![1](https://user-images.githubusercontent.com/45488781/170176845-2a2ebbb1-bbc2-425b-85e7-94710603f5f8.jpg)

**Comment by revelator** [comment]
win7 does not have the ucrt runtimes installed by default, try installing these -> https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c

**Comment by MagicGeeker** [comment]
> win7 does not have the ucrt runtimes installed by default, try installing these -> https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c

I tried but it seems does not work.And I can not find api-ms-win-core-path-l1-1-0.dll in Windows 10 also (search using Everything) but gdb works in Windows 10.

**Comment by revelator** [comment]
gdb might have been build with win10 as default target in that case it will most likely not work on win7, the msys2 project has ditched support for any windows versions below 10 so if you got it from there that might explain it. 
there is a fix for the missing dll here https://answers.microsoft.com/en-us/windows/forum/windows_7-update/windows-10-upgrader-appexe-system-error/29ef57a1-079c-424d-bbd7-78ffcc654b69

**Comment by revelator** [comment]
instead of copying in the renamed dll to that folder just copy it back after you have renamed the copy to the missing dll file.

**Comment by PNBRQK** [comment]
the reason for such failure might be that this build of gdb loads python scripts by default, and python 3.9+ in turn requires new Windows API function(s) like `PathCchCanonicalizeEx` from `api-ms-win-core-path-l1-1-0.dll` that aren't present on Win7.

Anyhow, go for https://github.com/nalexandru/api-ms-win-core-path-HACK and see whether his/her hack solves the problem.
