### ISSUE TITLE
How to localize GCC compiling message?

### ISSUE THREAD

**Issue by anbangli** [jmeubank/tdm-gcc#6]
GCC compiling message is always in English. But some of my Chinese student feel it is somewhat difficult to  understand the message. Can I do something to make the compiling message displayed in other language? Or, how to localize GCC compiling message?

**Comment by jmeubank** [comment]
I've built TDM-GCC according to upstream conventions and for reasons I haven't discovered yet, that includes the --disable-nls flag for TDM-GCC 64-bit.

https://github.com/gcc-mirror/gcc/tree/master/gcc/po is a list of available languages when `--enable-nls` is used. So, a new TDM-GCC 64-bit release with `--enable-nls` will provide this.

TDM-GCC 32-bit is built with `--enable-nls` and includes localized translations for zh_CN. https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html has information on how to affect localized diaganostic output with environment variables.

**Comment by jmeubank** [comment]
The upcoming TDM64 release will include all languages listed at https://github.com/gcc-mirror/gcc/tree/master/gcc/po .

**Comment by jmeubank** [comment]
TDM64 GCC 10.3.0 and binutils 2.36.1 include localization files.
