### ISSUE TITLE
'clock_gettime' [-Werror=implicit-function-declaration]|

### ISSUE THREAD

**Issue by privetryan** [jmeubank/tdm-gcc#8]
I have a program that cleanly compiles without warnings/errors using other MinGW but has error when using tdm-gcc. Refer below:
**-Werror enabled:**
<pre>
error: implicit declaration of function 'clock_gettime' [-Werror=implicit-function-declaration]
</pre>
**-Werror disabled:**
<pre>
undefined reference to `clock_gettime'
</pre>

Question:
1. Is this expected/unsupported/limitation of tdm-gcc?
2. Is this a bug?

**Comment by jmeubank** [comment]
This is due to:
https://github.com/jmeubank/mingw-w64/blob/v7.x.public/_PATCHES/mingw32.patch#L118

It was done for MinGW.org compatibility; we'll need to come up with a better fix.

**Comment by jmeubank** [comment]
This will be fixed in the upcoming TDM-GCC 10.3.0 release.
